In [ ]:
import torch

In [ ]:
torch.full(size=(1,4),fill_value=3)

tensor([[3, 3, 3, 3]])

In [ ]:
torch.full((4,4),4)

tensor([[4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4],
        [4, 4, 4, 4]])

In [ ]:
 torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 0.1, 10, torch.quint8)

tensor([-1.,  0.,  1.,  2.], size=(4,), dtype=torch.quint8,
       quantization_scheme=torch.per_tensor_affine, scale=0.1, zero_point=10)

In [ ]:
v1=torch.arange(1,10)
print(v1)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [ ]:
x=torch.rand(2,3)
z=torch.cat((x,x),1)

In [ ]:
z

tensor([[0.2144, 0.1280, 0.5235, 0.2144, 0.1280, 0.5235],
        [0.4917, 0.1376, 0.5542, 0.4917, 0.1376, 0.5542]])

In [ ]:
p=torch.chunk(v1,3)
p

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

In [ ]:
x=torch.tensor([1,11,111,1111])
y=torch.tensor([2,22,222,2222])
z=torch.tensor([3,33,333,3333])


a=torch.dstack((x,y,z))
a

tensor([[[   1,    2,    3],
         [  11,   22,   33],
         [ 111,  222,  333],
         [1111, 2222, 3333]]])

In [ ]:
z=torch.hstack((x,y,z))
z

tensor([   1,   11,  111, 1111,    2,   22,  222, 2222,    1,   11,  111, 1111,
           2,   22,  222, 2222,    3,   33,  333, 3333])

In [ ]:
g=torch.randn(size=(3,3))
g

tensor([[ 0.4717, -0.2438,  0.4300],
        [ 0.6205, -0.1656,  1.5217],
        [ 0.1492,  1.0504,  0.1096]])

In [ ]:
indices= torch.tensor([0,1])
torch.index_select(g,0,indices)

tensor([[ 0.4717, -0.2438,  0.4300],
        [ 0.6205, -0.1656,  1.5217]])

In [ ]:
 x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
 x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
torch.narrow(x,0,0,2)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
torch.narrow(x,1,0,2)

tensor([[1, 2],
        [4, 5],
        [7, 8]])

In [ ]:
z=torch.randn((2,4))

In [ ]:
torch.reshape(z,(4,2))

tensor([[-1.4313, -0.8502],
        [-0.0611,  0.9480],
        [-1.0807,  1.2921],
        [ 0.0779, -0.1566]])

In [ ]:
torch.reshape(z,(-1,))

tensor([-1.4313, -0.8502, -0.0611,  0.9480, -1.0807,  1.2921,  0.0779, -0.1566])

In [ ]:
torch.split(z,2)

(tensor([[-1.4313, -0.8502, -0.0611,  0.9480],
         [-1.0807,  1.2921,  0.0779, -0.1566]]),)

In [ ]:
torch.split(z[0],[1,3])

(tensor([-1.4313]), tensor([-0.8502, -0.0611,  0.9480]))

In [ ]:
x = torch.zeros(2, 1, 2, 1, 2)
x

In [ ]:
y=torch.squeeze(x)
y

In [ ]:
z

tensor([[-1.1281,  1.8095,  0.7791, -0.0798],
        [ 0.6227, -0.9656,  0.4888, -0.8167]])

In [ ]:
src = torch.tensor([[4, 3, 5],
                        [6, 7, 8]])
torch.take(z, torch.tensor([0, 2, 5]))

tensor([-1.1281,  0.7791, -0.9656])

In [ ]:
print(z)
tz=torch.transpose(z,0,1)
print(tz)

tensor([[-1.1281,  1.8095,  0.7791, -0.0798],
        [ 0.6227, -0.9656,  0.4888, -0.8167]])
tensor([[-1.1281,  0.6227],
        [ 1.8095, -0.9656],
        [ 0.7791,  0.4888],
        [-0.0798, -0.8167]])


In [ ]:
z=torch.randn(20)

torch.unsqueeze(z,0)

tensor([[ 0.3552,  0.5287,  0.2296,  0.6659,  0.0859, -0.6740, -0.0729, -0.8185,
          0.4527, -0.6840,  2.1190, -1.0108, -1.3610,  0.1997, -1.7407,  0.3037,
         -0.3642, -0.9036, -0.5357,  0.9127]])

In [ ]:
a=torch.tensor([1,3,9])
b=torch.tensor([2,6,10])

torch.vstack((a,b))

tensor([[ 1,  3,  9],
        [ 2,  6, 10]])

In [ ]:
a=torch.tensor([[1],[2],[3]])
b=torch.tensor([[4],[5],[6]])

torch.vstack((a,b))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [ ]:
x=torch.randn((3,2))
y=torch.ones((3,2))
print(x)
print(y)

tensor([[ 1.8440,  0.0987],
        [ 0.9712, -2.3696],
        [ 0.4552, -0.7348]])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [ ]:
torch.where(x>1,x,y)

tensor([[1.8440, 1.0000],
        [1.0000, 1.0000],
        [1.0000, 1.0000]])

In [ ]:
torch.where(x>1,y,x)

tensor([[ 1.0000,  0.0987],
        [ 0.9712, -2.3696],
        [ 0.4552, -0.7348]])

In [ ]:
torch.randint(3,10,(3,4))

tensor([[7, 9, 7, 6],
        [9, 8, 5, 3],
        [4, 3, 7, 5]])